# Project 9: Web Scraping, APIs & Wrappers (US Stocks)

## Web Scraping - the Dow Jones Constituents

In [1]:
import pandas as pd

In [2]:
pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")

[                                                   0  \
 0  Historical logarithmic graph of the DJIA from ...
 1                                         Foundation
 2                                           Operator
 3                                          Exchanges
 4                                     Trading symbol
 5                                       Constituents
 6                                               Type
 7                                         Market cap
 8                                   Weighting method
 9                                            Website

                                                    1
 0  Historical logarithmic graph of the DJIA from ...
 1  February 16, 1885; 136 years ago[1]May 26, 189...
 2                              S&P Dow Jones Indices
 3                      New York Stock ExchangeNASDAQ
 4                                  ^DJI$INDU.DJIDJIA
 5                                                 30
 6                                          Large cap
 7          US$10.84 trillion(as of July 30, 2021)[3]
 8                               Price-weighted index
 9  us.spindices.com/indices/equity/dow-jones-indu...  ,
                      Company Exchange Symbol                        Industry  \
 0                         3M     NYSE    MMM                    Conglomerate
 1           American Express     NYSE    AXP              Financial services
 2                      Amgen   NASDAQ   AMGN         Pharmaceutical industry
 3                 Apple Inc.   NASDAQ   AAPL          Information technology
 4                     Boeing     NYSE     BA           Aerospace and defense
 5           Caterpillar Inc.     NYSE    CAT         Construction and Mining
 6        Chevron Corporation     NYSE    CVX              Petroleum industry
 7              Cisco Systems   NASDAQ   CSCO          Information technology
 8      The Coca-Cola Company     NYSE     KO                   Food industry
 9                   Dow Inc.     NYSE    DOW               Chemical industry
 10             Goldman Sachs     NYSE     GS              Financial services
 11            The Home Depot     NYSE     HD                       Retailing
 12                 Honeywell   NASDAQ    HON                    Conglomerate
 13                       IBM     NYSE    IBM          Information technology
 14                     Intel   NASDAQ   INTC          Information technology
 15         Johnson & Johnson     NYSE    JNJ         Pharmaceutical industry
 16            JPMorgan Chase     NYSE    JPM              Financial services
 17                McDonald's     NYSE    MCD                   Food industry
 18               Merck & Co.     NYSE    MRK         Pharmaceutical industry
 19                 Microsoft   NASDAQ   MSFT          Information technology
 20                Nike, Inc.     NYSE    NKE                         Apparel
 21          Procter & Gamble     NYSE     PG      Fast-moving consumer goods
 22                Salesforce     NYSE    CRM          Information technology
 23   The Travelers Companies     NYSE    TRV              Financial services
 24        UnitedHealth Group     NYSE    UNH             Managed health care
 25    Verizon Communications     NYSE     VZ               Telecommunication
 26                 Visa Inc.     NYSE      V              Financial services
 27  Walgreens Boots Alliance   NASDAQ    WBA                       Retailing
 28                   Walmart     NYSE    WMT                       Retailing
 29   The Walt Disney Company     NYSE    DIS  Broadcasting and entertainment

     Date added                                  Notes Index weighting
 0   1976-08-09  As Minnesota Mining and Manufacturing           3.62%
 1   1982-08-30                                    NaN           3.00%
 2   2020-08-31                                    NaN           4.18%
 3   2015-03-19                                    NaN           2.78%
 4   1987-03-12                                    NaN           4.12%
 5   1991-05-06                                    NaN           3.96%
 6   2008-02-19          Also 1930-07-18 to 1999-11-01           1.82%
 7   2009-06-08                                    NaN           1.10%
 8   1987-03-12          Also 1932-05-26 to 1935-11-20           1.04%
 9   2019-04-02                                    NaN           1.18%
 10  2013-09-20                                    NaN           7.60%
 11  1999-11-01                                    NaN           6.05%
 12  2020-08-31                                    NaN           4.29%
 13  1979-06-29          Also 1932-05-26 to 1939-03-04           2.60%
 14  1999-11-01                                    NaN           1.00%
 15  1997-03-17                                    NaN           3.26%
 16  1991-05-06                                    NaN           2.93%
 17  1985-10-30                                    NaN           4.44%
 18  1979-06-29                                    NaN           1.45%
 19  1999-11-01                                    NaN           5.63%
 20  2013-09-20                                    NaN           3.16%
 21  1932-05-26                                    NaN           2.66%
 22  2020-08-31                                    NaN           4.83%
 23  2009-06-08                                    NaN           2.99%
 24  2012-09-24                                    NaN           7.88%
 25  2004-04-08                                    NaN           1.02%
 26  2013-09-20                                    NaN           4.36%
 27  2018-06-26                                    NaN           0.90%
 28  1997-03-17                                    NaN           2.77%
 29  1991-05-06                                    NaN           3.32%  ,
      Year  Closing value Change in points Change in percent
 0    1885          39.29            10.83             38.05
 1    1886          41.03             1.74              4.43
 2    1887          37.58            −3.45             −8.41
 3    1888          39.39             1.81              4.82
 4    1889          41.56             2.17              5.51
 ..    ...            ...              ...               ...
 131  2016       19762.60          2337.57             13.42
 132  2017       24719.22          4956.62             25.08
 133  2018       23327.46        −1,391.76             −5.63
 134  2019       28538.44          5210.98             22.34
 135  2020       30606.48          2068.04              7.25

 [136 rows x 4 columns],
     0                                                  1
 0 NaN  Wikimedia Commons has media related to Dow Jon...,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteComponents of the Dow Jones Industrial Average  \
 0  3M American Express Amgen Apple Boeing Caterpi...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteComponents of the Dow Jones Industrial Average.1
 0  3M American Express Amgen Apple Boeing Caterpi...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,
   vteMajor North and South American stock market indices  \
 0                                      United States
 1                                             Canada
 2                                             Mexico
 3                                           Colombia
 4                                             Brazil
 5                                              Chile
 6                                          Argentina
 7                                               Peru

   vteMajor North and South American stock market indices.1
 0  Dow Jones Industrial Average Dow Jones Transpo...
 1                 S&P/TSX 60 S&P/TSX Composite Index
 2                   Indice de Precios y Cotizaciones
 3  COLCAP Indice General de la Bolsa de Valores d...
 4                                     Índice Bovespa
 5             Índice de Precio Selectivo de Acciones
 6                                             MERVAL
 7                         S&P/BVL Peru General Index        ,
                                          vteNews Corp  \
 0                     Sister company: Fox Corporation
 1   vteDow Jones & CompanyNational consumer produc...
 2                              vteDow Jones & Company
 3                          National consumer products
 4                                 Enterprise products
 5   vteHarperCollinsUnited States Avon Caedmon Ecc...
 6                                    vteHarperCollins
 7                                       United States
 8                                      United Kingdom
 9                                           Australia
 10                                          Christian
 11                                             Canada
 12  vteNews Corp AustraliaNewspapersMetropolitan T...
 13                             vteNews Corp Australia
 14                                         Newspapers
 15                                       Metropolitan
 16                                           Regional
 17                                         Queensland
 18                                              Other
 19  vteNews Corp Australia community newspapersNew...
 20        vteNews Corp Australia community newspapers
 21                                    NewsLocal (NSW)
 22                                     Messenger (SA)
 23                                        Quest (Qld)
 24                                           Victoria
 25                                         Television
 26                                          Magazines
 27                                              Other
 28                                     Formerholdings
 29  vteNews UK The Times The Sunday Times The Sun ...
 30                                         vteNews UK
 31  The Times The Sunday Times The Sun The Times L...
 32                                       Other assets
 33      See also: 21st Century Fox · News Corporation

                                        vteNews Corp.1
 0                     Sister company: Fox Corporation
 1   vteDow Jones & CompanyNational consumer produc...
 2                              vteDow Jones & Company
 3   Barron's Financial News Investor's Business Da...
 4                Factiva S&P Dow Jones Indices (2.6%)
 5   vteHarperCollinsUnited States Avon Caedmon Ecc...
 6                                    vteHarperCollins
 7   Avon Caedmon Ecco Harper Harper Perennial I Ca...
 8   William Collins, Sons Collins Bartholomew The ...
 9                                   Angus & Robertson
 10  BibleGateway.com Thomas Nelson Women of Faith ...
 11           Harlequin Enterprises Love Inspired Mira
 12  vteNews Corp AustraliaNewspapersMetropolitan T...
 13                             vteNews Corp Australia
 14  Metropolitan The Australian The Daily Telegrap...
 15  The Australian The Daily Telegraph (Sydney) He...
 16  Queensland Balonne Beacon Bowen Independent Th...
 17  Balonne Beacon Bowen Independent The Cairns Po...
 18  The Coffs Coast Advocate The Daily Examiner Ge...
 19  vteNews Corp Australia community newspapersNew...
 20        vteNews Corp Australia community newspapers
 21  Manly Daily North Shore Times Northern Distric...
 22  News Review Leader Standard Eastern Courier Ea...
 23                      South-West News Southern Star
 24                        Leader Community Newspapers
 25  Sky News Live Sky News Extra Sky News Weather ...
 26            Big League GQ Australia Vogue Australia
 27  Brisbane Broncos (69%) Foxtel (65%) HT&E (15%)...
 28  Australian Associated Press (47%) ADS (Adelaid...
 29  vteNews UK The Times The Sunday Times The Sun ...
 30                                         vteNews UK
 31  The Times The Sunday Times The Sun The Times L...
 32  Move Realtor.com New York Post News America Ma...
 33      See also: 21st Century Fox · News Corporation  ,
        vteDow Jones & Company  \
 0  National consumer products
 1         Enterprise products

                             vteDow Jones & Company.1
 0  Barron's Financial News Investor's Business Da...
 1               Factiva S&P Dow Jones Indices (2.6%)  ,
   vteHarperCollins                                 vteHarperCollins.1
 0    United States  Avon Caedmon Ecco Harper Harper Perennial I Ca...
 1   United Kingdom  William Collins, Sons Collins Bartholomew The ...
 2        Australia                                  Angus & Robertson
 3        Christian  BibleGateway.com Thomas Nelson Women of Faith ...
 4           Canada           Harlequin Enterprises Love Inspired Mira,
                                vteNews Corp Australia  \
 0                                          Newspapers
 1                                        Metropolitan
 2                                            Regional
 3                                          Queensland
 4                                               Other
 5   vteNews Corp Australia community newspapersNew...
 6         vteNews Corp Australia community newspapers
 7                                     NewsLocal (NSW)
 8                                      Messenger (SA)
 9                                         Quest (Qld)
 10                                           Victoria
 11                                         Television
 12                                          Magazines
 13                                              Other
 14                                     Formerholdings

                              vteNews Corp Australia.1
 0   Metropolitan The Australian The Daily Telegrap...
 1   The Australian The Daily Telegraph (Sydney) He...
 2   Queensland Balonne Beacon Bowen Independent Th...
 3   Balonne Beacon Bowen Independent The Cairns Po...
 4   The Coffs Coast Advocate The Daily Examiner Ge...
 5   vteNews Corp Australia community newspapersNew...
 6         vteNews Corp Australia community newspapers
 7   Manly Daily North Shore Times Northern Distric...
 8   News Review Leader Standard Eastern Courier Ea...
 9                       South-West News Southern Star
 10                        Leader Community Newspapers
 11  Sky News Live Sky News Extra Sky News Weather ...
 12            Big League GQ Australia Vogue Australia
 13  Brisbane Broncos (69%) Foxtel (65%) HT&E (15%)...
 14  Australian Associated Press (47%) ADS (Adelaid...  ,
                                                    0  \
 0                                       Metropolitan
 1                                           Regional
 2                                         Queensland
 3                                              Other
 4  vteNews Corp Australia community newspapersNew...
 5        vteNews Corp Australia community newspapers
 6                                    NewsLocal (NSW)
 7                                     Messenger (SA)
 8                                        Quest (Qld)
 9                                           Victoria

                                                    1
 0  The Australian The Daily Telegraph (Sydney) He...
 1  Queensland Balonne Beacon Bowen Independent Th...
 2  Balonne Beacon Bowen Independent The Cairns Po...
 3  The Coffs Coast Advocate The Daily Examiner Ge...
 4  vteNews Corp Australia community newspapersNew...
 5        vteNews Corp Australia community newspapers
 6  Manly Daily North Shore Times Northern Distric...
 7  News Review Leader Standard Eastern Courier Ea...
 8                      South-West News Southern Star
 9                        Leader Community Newspapers  ,
             0                                                  1
 0  Queensland  Balonne Beacon Bowen Independent The Cairns Po...
 1       Other  The Coffs Coast Advocate The Daily Examiner Ge...,
   vteNews Corp Australia community newspapers  \
 0                             NewsLocal (NSW)
 1                              Messenger (SA)
 2                                 Quest (Qld)
 3                                    Victoria

        vteNews Corp Australia community newspapers.1
 0  Manly Daily North Shore Times Northern Distric...
 1  News Review Leader Standard Eastern Courier Ea...
 2                      South-West News Southern Star
 3                        Leader Community Newspapers  ,
                                           vteNews UK  \
 0  The Times The Sunday Times The Sun The Times L...

                                         vteNews UK.1
 0  The Times The Sunday Times The Sun The Times L...  ]

In [26]:
const = pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")[1]

In [4]:
const

,Company,Exchange,Symbol,Industry,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.62%
1,American Express,NYSE,AXP,Financial services,1982-08-30,NaN,3.00%
2,Amgen,NASDAQ,AMGN,Pharmaceutical industry,2020-08-31,NaN,4.18%
3,Apple Inc.,NASDAQ,AAPL,Information technology,2015-03-19,NaN,2.78%
4,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,NaN,4.12%
5,Caterpillar Inc.,NYSE,CAT,Construction and Mining,1991-05-06,NaN,3.96%
6,Chevron Corporation,NYSE,CVX,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,1.82%
7,Cisco Systems,NASDAQ,CSCO,Information technology,2009-06-08,NaN,1.10%
8,The Coca-Cola Company,NYSE,KO,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
9,Dow Inc.,NYSE,DOW,Chemical industry,2019-04-02,NaN,1.18%
10,Goldman Sachs,NYSE,GS,Financial services,2013-09-20,NaN,7.60%
11,The Home Depot,NYSE,HD,Retailing,1999-11-01,NaN,6.05%
12,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,NaN,4.29%
13,IBM,NYSE,IBM,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.60%
14,Intel,NASDAQ,INTC,Information technology,1999-11-01,NaN,1.00%
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,NaN,3.26%
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,NaN,2.93%
17,McDonald's,NYSE,MCD,Food industry,1985-10-30,NaN,4.44%
18,Merck & Co.,NYSE,MRK,Pharmaceutical industry,1979-06-29,NaN,1.45%
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,5.63%
20,"Nike, Inc.",NYSE,NKE,Apparel,2013-09-20,NaN,3.16%
21,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,NaN,2.66%
22,Salesforce,NYSE,CRM,Information technology,2020-08-31,NaN,4.83%
23,The Travelers Companies,NYSE,TRV,Financial services,2009-06-08,NaN,2.99%
24,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24,NaN,7.88%
25,Verizon Communications,NYSE,VZ,Telecommunication,2004-04-08,NaN,1.02%
26,Visa Inc.,NYSE,V,Financial services,2013-09-20,NaN,4.36%
27,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26,NaN,0.90%
28,Walmart,NYSE,WMT,Retailing,1997-03-17,NaN,2.77%
29,The Walt Disney Company,NYSE,DIS,Broadcasting and entertainment,1991-05-06,NaN,3.32%

In [27]:
const = const.iloc[:, :5].copy()
const

,Company,Exchange,Symbol,Industry,Date added
0,3M,NYSE,MMM,Conglomerate,1976-08-09
1,American Express,NYSE,AXP,Financial services,1982-08-30
2,Amgen,NASDAQ,AMGN,Pharmaceutical industry,2020-08-31
3,Apple Inc.,NASDAQ,AAPL,Information technology,2015-03-19
4,Boeing,NYSE,BA,Aerospace and defense,1987-03-12
5,Caterpillar Inc.,NYSE,CAT,Construction and Mining,1991-05-06
6,Chevron Corporation,NYSE,CVX,Petroleum industry,2008-02-19
7,Cisco Systems,NASDAQ,CSCO,Information technology,2009-06-08
8,The Coca-Cola Company,NYSE,KO,Food industry,1987-03-12
9,Dow Inc.,NYSE,DOW,Chemical industry,2019-04-02
10,Goldman Sachs,NYSE,GS,Financial services,2013-09-20
11,The Home Depot,NYSE,HD,Retailing,1999-11-01
12,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31
13,IBM,NYSE,IBM,Information technology,1979-06-29
14,Intel,NASDAQ,INTC,Information technology,1999-11-01
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06
17,McDonald's,NYSE,MCD,Food industry,1985-10-30
18,Merck & Co.,NYSE,MRK,Pharmaceutical industry,1979-06-29
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01
20,"Nike, Inc.",NYSE,NKE,Apparel,2013-09-20
21,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26
22,Salesforce,NYSE,CRM,Information technology,2020-08-31
23,The Travelers Companies,NYSE,TRV,Financial services,2009-06-08
24,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24
25,Verizon Communications,NYSE,VZ,Telecommunication,2004-04-08
26,Visa Inc.,NYSE,V,Financial services,2013-09-20
27,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26
28,Walmart,NYSE,WMT,Retailing,1997-03-17
29,The Walt Disney Company,NYSE,DIS,Broadcasting and entertainment,1991-05-06

In [28]:
const.rename(columns = {"Date added":"Date_Added"}, inplace = True)

In [29]:
const.Date_Added = pd.to_datetime(const.Date_Added)

In [30]:
const.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
Company       30 non-null object
Exchange      30 non-null object
Symbol        30 non-null object
Industry      30 non-null object
Date_Added    30 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 1.3+ KB

## Normalizing Unicode Strings and Getting the Ticker Symbols

In [31]:
import unicodedata

In [32]:
const.Symbol

0      MMM
1      AXP
2     AMGN
3     AAPL
4       BA
5      CAT
6      CVX
7     CSCO
8       KO
9      DOW
10      GS
11      HD
12     HON
13     IBM
14    INTC
15     JNJ
16     JPM
17     MCD
18     MRK
19    MSFT
20     NKE
21      PG
22     CRM
23     TRV
24     UNH
25      VZ
26       V
27     WBA
28     WMT
29     DIS
Name: Symbol, dtype: object

In [34]:
const.Symbol[1]

'AXP'

In [11]:
const.Symbol.to_list()

['MMM',
 'AXP',
 'AMGN',
 'AAPL',
 'BA',
 'CAT',
 'CVX',
 'CSCO',
 'KO',
 'DOW',
 'GS',
 'HD',
 'HON',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'MCD',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'CRM',
 'TRV',
 'UNH',
 'VZ',
 'V',
 'WBA',
 'WMT',
 'DIS']

In [12]:
const.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
Company       30 non-null object
Exchange      30 non-null object
Symbol        30 non-null object
Industry      30 non-null object
Date_Added    30 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 1.3+ KB

In [13]:
const.Symbol.apply(lambda x: unicodedata.normalize("NFKD", x))

0      MMM
1      AXP
2     AMGN
3     AAPL
4       BA
5      CAT
6      CVX
7     CSCO
8       KO
9      DOW
10      GS
11      HD
12     HON
13     IBM
14    INTC
15     JNJ
16     JPM
17     MCD
18     MRK
19    MSFT
20     NKE
21      PG
22     CRM
23     TRV
24     UNH
25      VZ
26       V
27     WBA
28     WMT
29     DIS
Name: Symbol, dtype: object

In [14]:
const.Symbol = const.Symbol.apply(lambda x: unicodedata.normalize("NFKD", x))

In [15]:
const.Symbol[0]

'MMM'

In [16]:
const["Ticker"] = const.Symbol.str.split(": ").apply(lambda x: x[-1])

In [17]:
const

,Company,Exchange,Symbol,Industry,Date_Added,Ticker
0,3M,NYSE,MMM,Conglomerate,1976-08-09,MMM
1,American Express,NYSE,AXP,Financial services,1982-08-30,AXP
2,Amgen,NASDAQ,AMGN,Pharmaceutical industry,2020-08-31,AMGN
3,Apple Inc.,NASDAQ,AAPL,Information technology,2015-03-19,AAPL
4,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,BA
5,Caterpillar Inc.,NYSE,CAT,Construction and Mining,1991-05-06,CAT
6,Chevron Corporation,NYSE,CVX,Petroleum industry,2008-02-19,CVX
7,Cisco Systems,NASDAQ,CSCO,Information technology,2009-06-08,CSCO
8,The Coca-Cola Company,NYSE,KO,Food industry,1987-03-12,KO
9,Dow Inc.,NYSE,DOW,Chemical industry,2019-04-02,DOW
10,Goldman Sachs,NYSE,GS,Financial services,2013-09-20,GS
11,The Home Depot,NYSE,HD,Retailing,1999-11-01,HD
12,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,HON
13,IBM,NYSE,IBM,Information technology,1979-06-29,IBM
14,Intel,NASDAQ,INTC,Information technology,1999-11-01,INTC
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,JNJ
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,JPM
17,McDonald's,NYSE,MCD,Food industry,1985-10-30,MCD
18,Merck & Co.,NYSE,MRK,Pharmaceutical industry,1979-06-29,MRK
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,MSFT
20,"Nike, Inc.",NYSE,NKE,Apparel,2013-09-20,NKE
21,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,PG
22,Salesforce,NYSE,CRM,Information technology,2020-08-31,CRM
23,The Travelers Companies,NYSE,TRV,Financial services,2009-06-08,TRV
24,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24,UNH
25,Verizon Communications,NYSE,VZ,Telecommunication,2004-04-08,VZ
26,Visa Inc.,NYSE,V,Financial services,2013-09-20,V
27,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26,WBA
28,Walmart,NYSE,WMT,Retailing,1997-03-17,WMT
29,The Walt Disney Company,NYSE,DIS,Broadcasting and entertainment,1991-05-06,DIS

In [18]:
ticker_list = const.Ticker.to_list()

In [19]:
ticker_list

['MMM',
 'AXP',
 'AMGN',
 'AAPL',
 'BA',
 'CAT',
 'CVX',
 'CSCO',
 'KO',
 'DOW',
 'GS',
 'HD',
 'HON',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'MCD',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'CRM',
 'TRV',
 'UNH',
 'VZ',
 'V',
 'WBA',
 'WMT',
 'DIS']

In [20]:
const.to_csv("const.csv", index = False)

## Loading and Saving Historical Stock Prices

In [35]:
import pandas as pd
import yfinance as yf

ModuleNotFoundError: No module named 'yfinance'

In [27]:
ticker_list

['MMM',
 'AXP',
 'AMGN',
 'AAPL',
 'BA',
 'CAT',
 'CVX',
 'CSCO',
 'KO',
 'DOW',
 'GS',
 'HD',
 'HON',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'MCD',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'CRM',
 'TRV',
 'UNH',
 'VZ',
 'V',
 'WBA',
 'WMT',
 'DIS']

In [ ]:
prices = yf.download(ticker_list, start = "2007-01-01", end = "2020-03-31")

In [ ]:
prices

In [ ]:
prices.info()

In [ ]:
prices = prices.loc[:,"Close"].copy()

In [ ]:
prices.info()

In [ ]:
prices

In [ ]:
prices.to_csv("const_prices.csv")

In [ ]:
dji = yf.download("^DJI", start = "2007-01-01",  end = "2020-03-31")

In [ ]:
dji

In [ ]:
dji.to_csv("dji.csv")